"""empty message

Revision ID: 48171ac1ab6f
Revises: 
Create Date: 2021-01-31 00:09:02.332538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48171ac1ab6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'id')
    op.drop_column('actors', 'id')
    # ### end Alembic commands ###
